[project]
name = "soma-env-0.0"
channels = ["pytorch", "nvidia", "conda-forge", "https://brainvisa.info/neuro-forge"]
platforms = ["linux-64"]
version = "0.0"

[dependencies]
python = ">=3.10,==3.11,>=3.9"
typer = "*"
conda-build = "*"
pyyaml = "*"
dateutils = "*"
cmake = "*"
gcc = "<15"
git = "*"
git-lfs="*"
gitpython = "*"
gxx = "<15"
libglu = "*"
libglvnd-devel-cos7-x86_64 = "*"
libstdcxx-devel_linux-64 = "*"
make = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesalib-devel-only = "*"
pip = "*"
pyaml = "*"
pytest = "*"
rattler-build = ">=0.13"
six = "*"
sphinx = "*"
toml = "*"
virtualgl = "*"
"sigcpp-2.0" = "*"
libblitz = "*"
boost-cpp = "*"
gfortran = "*"
dcmtk = "*"
numpy = "<2"
libminc = "*"
openjpeg = "*"
pywebp = "*"
objgraph = "*"
graphviz = "*"
doxygen = "*"
pkgconfig = "*"
nipype = "*"
xlrd = "*"
xlwt = "*"
openpyxl = "*"
lark-parser = ">0.7.0"
python-dateutil = "*"
requests = "*"
cryptography = "*"
pytorch = "*"
torchvision = "*"
scikit-learn = "*"
pcl = "*"
configobj = "*"
pyqtwebkit = "*"
scipy = "*"
traits = { version = "<7", build = "*" }
spm12 = "*"
reportlab = "*"
libsvm = "*"
qwt = "*"
matplotlib = "*"
qtconsole = "*"
ipycanvas = "*"
ipywidgets = "*"
ipyevents = "*"
notebook = "*"
pygltflib = "*"
nodejs = "*"
xvfb = "*"
mesalib_software = "*"
pydantic = "<2"
pyqt = "*"
pyqtwebengine = "*"
ipykernel = "<7"
pycryptodome = "*"
pandas = "*"
libgl = "*"
libopengl = "*"
pydicom = "*"
pre-commit = "<5,>=4.1.0"
scikit-image = "*"
gdb = "*"
sphinxcontrib-mermaid = "*"
myst-parser = "*"
sphinx-rtd-theme = "*"
sphinx-gallery = "*"
nbsphinx = "*"
nbconvert-pandoc = "*"
gltf-transform = "*"

[dependencies.libjpeg-turbo]
channel = "conda-forge"
version = ">=3.0.0"

[pypi-dependencies]
dracopy = ">=1.4.2"

[activation]
scripts = ["activate.sh"]
